# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: 다은 호스팅
site_url: https://hosting.da-eun.com/
site_author: Da-eun
site_description: >-
  웹사이트, 도메인 연결, 데이터베이스, 이메일 등을 무제한 추가할 수 있는 호스팅을 제공합니다.
  서버에 대한 지식없이도 관리툴을 이용하여 손쉽게 이용할 수 있습니다.

# Repository
repo_name: stone-creator/mkdocs-material
repo_url: https://github.com/stone-creator/mkdocs-material
edit_uri: "edit/sc-main/docs/"

# Copyright
copyright: "다은 | 이헌기 | 010-6836-5648 | support@da-eun.com | (489O3) 부산시 중구 망양로277번길 4<br />
사업자등록번호: 106-28-51344 | 통신판매업신고번호: 2020-부산중구-0181 | 개인정보보호책임자: 이헌기 (010-6836-5648, support@da-eun.com)<br />
Copyright &copy; 2022 Hosting.da-eun.com"

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: kr
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  # icon:
  #   logo: logo
  logo: assets/logo.png

# Plugins
plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       conventions.md: philosophy.md
  #       reference/meta-tags.md: reference/index.md
  #       reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
  #       sponsorship.md: insiders/index.md
  #       upgrading.md: upgrade.md
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: G-FY2F328Y9K
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/squidfunk
  #   - icon: fontawesome/brands/gitter
  #     link: https://gitter.im/squidfunk/mkdocs-material
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# Page tree
# nav:
#   - Home: index.md
#   - Getting started:
#     - Installation: getting-started.md
#     - Creating your site: creating-your-site.md
#     - Publishing your site: publishing-your-site.md
#     - Customization: customization.md
#     - Browser support: browser-support.md
#     - Philosophy: philosophy.md
#     - Alternatives: alternatives.md
#     - License: license.md
#     - Changelog:
#       - changelog/index.md
#       - How to upgrade: upgrade.md
#   - Setup:
#     - Changing the colors: setup/changing-the-colors.md
#     - Changing the fonts: setup/changing-the-fonts.md
#     - Changing the language: setup/changing-the-language.md
#     - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#     - Ensuring data privacy: setup/ensuring-data-privacy.md
#     - Setting up navigation: setup/setting-up-navigation.md
#     - Setting up site search: setup/setting-up-site-search.md
#     - Setting up site analytics: setup/setting-up-site-analytics.md
#     - Setting up social cards: setup/setting-up-social-cards.md
#     - Setting up tags: setup/setting-up-tags.md
#     - Setting up versioning: setup/setting-up-versioning.md
#     - Setting up the header: setup/setting-up-the-header.md
#     - Setting up the footer: setup/setting-up-the-footer.md
#     - Adding a git repository: setup/adding-a-git-repository.md
#     - Adding a comment system: setup/adding-a-comment-system.md
#     - Building for offline usage: setup/building-for-offline-usage.md
#     - Extensions:
#       - setup/extensions/index.md
#       - Python Markdown: setup/extensions/python-markdown.md
#       - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
#   - Reference:
#     - reference/index.md
#     - Abbreviations: reference/abbreviations.md
#     - Admonitions: reference/admonitions.md
#     - Annotations: reference/annotations.md
#     - Buttons: reference/buttons.md
#     - Code blocks: reference/code-blocks.md
#     - Content tabs: reference/content-tabs.md
#     - Data tables: reference/data-tables.md
#     - Diagrams: reference/diagrams.md
#     - Footnotes: reference/footnotes.md
#     - Formatting: reference/formatting.md
#     - Grids: reference/grids.md
#     - Icons, Emojis: reference/icons-emojis.md
#     - Images: reference/images.md
#     - Lists: reference/lists.md
#     - MathJax: reference/mathjax.md
#   - Insiders:
#     - insiders/index.md
#     - Getting started:
#       - Installation: insiders/getting-started.md
#       - Changelog: insiders/changelog.md
#   - Blog:
#     - blog/index.md
#     - 2021:
#       - blog/2021/the-past-present-and-future.md
#       - blog/2021/excluding-content-from-search.md
#       - blog/2021/search-better-faster-smaller.md

nav:
  - Home: index.md
  # - Intro: intro.md
  - Price:
    - price/price.md
    - price/price_more.md
  - Detail: detail.md
  # - Support: support.md
  - Docs: docs.md
  - Chat: https://da-eun.channel.io" target="_blank
  - Support: https://support.da-eun.com" target="_blank
  - Contact: contact.md
  - Privacy: privacy.md
  - Terms: terms.md
  - Blog:
    - blog/index.md
    - 2022:
      - blog/2022/index.md
      - blog/2022/2022-04-23-다은-호스팅-특징.md
      - blog/2022/2022-04-21-프리랜서-웹디자이너를-위한-재능마켓-종류.md

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/channel.js
